Import("env")

sources = [
    "test_lattice.cpp",
    "test_layout.cpp",
    ]

env = env.Clone()
env.Append(LIBS=["pyQCDcore"])

for source in sources:
    env.Program(target=source.rstrip(".cpp"), source=[source])